role_list = [
        [1, "Assassin", "White", "Village"],
        [2, "Druid", "White", "Village"],
        [3, "Ghoul", "White", "Vampires"],
        [4, "Guard", "White", "Village"],
        [5, "Guard (corrupted)", "Black", "Village"],
        [6, "Harlot", "Black", "Village"],
        [7, "Healer", "Blue", "Village"],
        [8, "Innkeeper", "White", "Village"],
        [9, "Juliet", "White", "Village"],
        [10, "Lawyer", "White", "Village"],
        [11, "Madman", "White", "Village"],
        [12, "Mage", "Blue", "Village"],
        [13, "Mage (black)", "Blue Black", "Opponent"],
        [14, "Major", "White", "Village"],
        [15, "Medium", "Blue", "Village"],
        [16, "Merchant", "White", "Village"],
        [17, "Orator", "White", "Village"],
        [18, "Peasant", "White", "Village"],
        [19, "Peasant (hero)", "White", "Village"],
        [20, "Peasant (wolf)", "White", "Village"],
        [21, "Priest", "White", "Village"],
        [22, "Psychic", "Blue", "Village"],
        [23, "Sinner", "White", "Village"],
        [24, "Spy", "White", "Village"],
        [25, "Traitor", "White", "Wolves"],
        [26, "Vampire", "Black", "Vampires"],
        [27, "Vampire slayer", "White", "Village"],
        [28, "Witch", "Blue", "Village"],
        [29, "Witch (black)", "Blue Black", "Opponent"],
        [30, "Wolf 1", "Black", "Wolves"],
        [31, "Wolf 2", "Black", "Wolves"],
        [32, "Wolf 3", "Black", "Wolves"],
]

role_list_complete = [
        [1, "Assassin", "White", "Village"],
        [2, "Druid", "White", "Village"],
        [3, "Ghoul", "White", "Vampires"],
        [4, "Guard", "White", "Village"],
        [5, "Guard (corrupted)", "Black", "Village"],
        [6, "Harlot", "Black", "Village"],
        [7, "Healer", "Blue", "Village"],
        [8, "Innkeeper", "White", "Village"],
        [9, "Juliet", "White", "Village"],
        [10, "Lawyer", "White", "Village"],
        [11, "Madman", "White", "Village"],
        [12, "Madman (healer)", "White", "Village"],
        [13, "Madman (mage)", "White", "Village"],
        [14, "Madman (mage black)", "White", "Village"],
        [15, "Madman (medium)", "White", "Village"],
        [16, "Madman (psychic)", "White", "Village"],
        [17, "Madman (witch)", "White", "Village"],
        [18, "Madman (witch black)", "White", "Village"],
        [19, "Mage", "Blue", "Village"],
        [20, "Mage (black)", "Blue Black", "Opponent"],
        [21, "Major", "White", "Village"],
        [22, "Medium", "Blue", "Village"],
        [23, "Merchant", "White", "Village"],
        [24, "Orator", "White", "Village"],
        [25, "Peasant", "White", "Village"],
        [26, "Peasant (hero)", "White", "Village"],
        [27, "Peasant (wolf)", "White", "Village"],
        [28, "Priest", "White", "Village"],
        [29, "Psychic", "Blue", "Village"],
        [30, "Sinner", "White", "Village"],
        [31, "Spy", "White", "Village"],
        [32, "Traitor", "White", "Wolves"],
        [33, "Vampire", "Black", "Vampires"],
        [34, "Vampire slayer", "White", "Village"],
        [35, "Vampirized", "Black", "Vampires"],
        [36, "Witch", "Blue", "Village"],
        [37, "Witch (black)", "Blue Black", "Opponent"],
        [38, "Wolf 1", "Black", "Wolves"],
        [39, "Wolf 2", "Black", "Wolves"],
        [40, "Wolf 3", "Black", "Wolves"],
        [41, "Wolf 4", "Black", "Wolves"],
]

madman_list = [    
        [1, "Madman (healer)"],
        [2, "Madman (mage)"],
        [3, "Madman (mage black)"],
        [4, "Madman (medium)"],
        [5, "Madman (psychic)"],
        [6, "Madman (witch)"],
        [7, "Madman (witch black)"],
]
